apiVersion: v1
name: supernoded
version: 0.0.1
description: An n2n supernode management daemon.
type: application
home: https://pojntfx.github.io/gon2n/
sources:
  - git@github.com:pojntfx/gon2n.git
maintainers:
  - name: Felix Pojtinger
    email: felix@pojtinger.com
    url: https://felix.pojtinger.com
appVersion: 0.0.1
